#!/usr/bin/env bash

if [ ! -f goinstall ]; then
echo 'goinstall must be run within its container folder' 1>&2
exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$HOME/go:$CURDIR"

gofmt -w src
go install $2 $1

export GOPATH="$OLDGOPATH"
echo 'Go install' $1 'finished'